name: Generate Datas
on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow pushing to the repository

    steps:
      # Step to clear cache
      - name: Clear cache
        run: rm -rf dist/*

      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif

        with:
          github_user_name: dita-deb  # Your GitHub username
          svg_out_path: dist/github-contribution-grid-snake.svg

      # GitHub Pages Action to publish the Snake SVG
      - uses: crazy-max/ghaction-github-pages@v3.0.0  # Use the latest version for node16/node20 compatibility
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure token has correct permissions
